package com.solana.core

import com.solana.bip32.Network
import com.solana.bip32.wallet.Bip44
import com.solana.bip32.wallet.CoinType
import com.solana.bip32.wallet.HdAddress
import com.solana.vendor.TweetNaclFast
import org.bitcoinj.crypto.*
import java.nio.ByteBuffer
import java.util.*


sealed class DerivationPath(val path: String) {
    object M_44H_501H_0H_0H : DerivationPath("M/44H/501H/0H/0H")
}

class Account {
    private var keyPair: TweetNaclFast.Signature.KeyPair

    constructor() {
        keyPair = TweetNaclFast.Signature.keyPair()
    }

    constructor(secretKey: ByteArray) {
        keyPair = TweetNaclFast.Signature.keyPair_fromSecretKey(secretKey)
    }

    private constructor(keyPair: TweetNaclFast.Signature.KeyPair) {
        this.keyPair = keyPair
    }

    val publicKey: PublicKey
        get() = PublicKey(keyPair.publicKey)
    val secretKey: ByteArray
        get() = keyPair.secretKey

    companion object {
        fun fromXX(words: List<String>, passphrase: String): Account {
            val bip44 = Bip44()
            val seed = MnemonicCode.toSeed(words, passphrase)
            val address: HdAddress =
                bip44.getRootAddressFromSeed(seed, Network.mainnet, CoinType.solana)

            return Account(TweetNaclFast.Signature.keyPair_fromSeed(address.privateKey.privateKey))
        }


        fun fromMnemonic(words: List<String>, passphrase: String, derivationPath: DerivationPath = DerivationPath.M_44H_501H_0H_0H): Account {
            val seed = MnemonicCode.toSeed(words, passphrase)
            val masterPrivateKey = HDKeyDerivation.createMasterPrivateKey(seed)
            val deterministicHierarchy = DeterministicHierarchy(masterPrivateKey)
            val child = deterministicHierarchy[HDUtils.parsePath(derivationPath.path), true, true]
            val keyPair = TweetNaclFast.Signature.keyPair_fromSeed(child.privKeyBytes)
            return Account(keyPair)
        }

        /**
         * Derive a Solana account from a Mnemonic generated by the Solana CLI
         * @param words seed words
         * @param passphrase seed passphrase
         * @return Solana account
         */
        fun fromBip39Mnemonic(words: List<String>, passphrase: String): Account {
            val seed = MnemonicCode.toSeed(words, passphrase)
            val keyPair = TweetNaclFast.Signature.keyPair_fromSeed(seed)
            return Account(keyPair)
        }

        /**
         * Creates an [Account] object from a Sollet-exported JSON string (array)
         * @param json Sollet-exported JSON string (array)
         * @return [Account] built from Sollet-exported private key
         */
        fun fromJson(json: String): Account {
            return Account(convertJsonStringToByteArray(json))
        }

        /**
         * Convert's a Sollet-exported JSON string into a byte array usable for [Account] instantiation
         * @param characters Sollet-exported JSON string
         * @return byte array usable in [Account] instantiation
         */
        private fun convertJsonStringToByteArray(characters: String): ByteArray {
            // Create resulting byte array
            val buffer = ByteBuffer.allocate(64)

            // Convert json array into String array
            val sanitizedJson = characters.replace("\\[".toRegex(), "").replace("]".toRegex(), "")
            val chars = sanitizedJson.split(",").toTypedArray()

            // Convert each String character into byte and put it in the buffer
            Arrays.stream(chars).forEach { character: String ->
                val byteValue = character.toInt().toByte()
                buffer.put(byteValue)
            }
            return buffer.array()
        }
    }
}